// Auto-generated by sync-templates.js - DO NOT EDIT MANUALLY
// This file is regenerated every time you run: npm run sync:templates
// To add a new component, just add it to CLI templates and re-sync

import { Alert } from "../../ui/Alert";
import { Badge } from "../../ui/Badge";
import { Button } from "../../ui/Button";
import { Card } from "../../ui/Card";
import { Checkbox } from "../../ui/Checkbox";
import { Input } from "../../ui/Input";
import { Radio } from "../../ui/Radio";
import { Spinner } from "../../ui/Spinner";
import { Switch } from "../../ui/Switch";
import { Textarea } from "../../ui/Textarea";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentMap: Record<string, React.ComponentType<any>> = {
  alert: Alert,
  badge: Badge,
  button: Button,
  card: Card,
  checkbox: Checkbox,
  input: Input,
  radio: Radio,
  spinner: Spinner,
  switch: Switch,
  textarea: Textarea,
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getComponent(slug: string): React.ComponentType<any> | null {
  return componentMap[slug] || null;
}
